export const CREATE_TWEET = "CREATE_TWEET";
export const GET_TWEET = "GET_TWEET";
export const UPDATE_TWEET = "UPDATE_TWEET";
export const DELETE_TWEET = "DELETE_TWEET";
export const SELECT_TWEET = "SELECT_TWEET";
export const CLEAR_TWEET = "CLEAR_TWEET";
export const DELETE_SELECTED_TWEET = "DELETE_SELECTED_TWEET";